[package]
name = "vhost-device-gpio"
version = "0.1.0"
authors = ["Viresh Kumar <viresh.kumar@linaro.org>"]
description = "vhost gpio backend device"
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["gpio", "vhost", "virt", "backend"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
xen = ["vm-memory/xen", "vhost/xen", "vhost-user-backend/xen"]
mock_gpio = []

[dependencies]
clap = { version = "4.5",  features = ["derive"] }
env_logger = "0.11"
libc = "0.2"
log = "0.4"
thiserror = "2.0"
vhost = { version = "0.13", features = ["vhost-user-backend"] }
vhost-user-backend = "0.17"
virtio-bindings = "0.2.5"
virtio-queue = "0.14"
vm-memory = "0.16.2"
vmm-sys-util = "0.14"

[target.'cfg(target_env = "gnu")'.dependencies]
libgpiod = "0.2"

[dev-dependencies]
assert_matches = "1.5"
virtio-queue = { version = "0.14", features = ["test-utils"] }
vm-memory = { version = "0.16.2", features = ["backend-mmap", "backend-atomic"] }
