[package]
name = "vhost-device-sound"
version = "0.1.0"
authors = ["Stefano Garzarella <sgarzare@redhat.com>", "Manos Pitsidianakis <manos.pitsidianakis@linaro.org>"]
description = "A virtio-sound device using the vhost-user protocol."
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["vhost", "sound", "virtio-sound", "virtio-snd", "virtio"]
categories = ["multimedia::audio", "virtualization"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2018"

[features]
xen = ["vm-memory/xen", "vhost/xen", "vhost-user-backend/xen"]
default = ["alsa-backend", "pw-backend"]
alsa-backend = ["dep:alsa"]
pw-backend = ["pw"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
thiserror = "1.0"
vhost = { version = "0.10", features = ["vhost-user-backend"] }
vhost-user-backend = "0.12"
virtio-bindings = "0.2.1"
virtio-queue = "0.11"
vm-memory = "0.14.0"
vmm-sys-util = "0.12"

# Make alsa and pipewire backends available only on gnu
[target.'cfg(target_env = "gnu")'.dependencies]
alsa = { version = "0.8", optional = true }
pw = { package = "pipewire", git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs.git", rev = "5fe090b3ac8f6fed756c4871ac18f26edda3ac89", optional = true }

[dev-dependencies]
rstest = "0.18.2"
tempfile = "3.9"
virtio-queue = { version = "0.11", features = ["test-utils"] }
vm-memory = { version = "0.14.0", features = ["backend-mmap", "backend-atomic"] }
