[package]
name = "vhost-device-rng"
version = "0.1.0"
authors = ["Mathieu Poirier <mathieu.poirier@linaro.org>"]
description = "vhost RNG backend device"
repository = "https://github.com/rust-vmm/vhost-device"
readme = "README.md"
keywords = ["rng", "vhost", "virt", "backend"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

[features]
xen = ["vm-memory/xen", "vhost/xen", "vhost-user-backend/xen"]

[dependencies]
clap = { version = "4.4",  features = ["derive"] }
env_logger = "0.10"
epoll = "4.3"
libc = "0.2"
log = "0.4"
rand = "0.8.5"
tempfile = "3.8"
thiserror = "1.0"
vhost = { version = "0.8", features = ["vhost-user-slave"] }
vhost-user-backend = "0.11"
virtio-bindings = "0.2.1"
virtio-queue = "0.10"
vm-memory = "0.13"
vmm-sys-util = "0.11"

[dev-dependencies]
assert_matches = "1.5"
virtio-queue = { version = "0.10", features = ["test-utils"] }
vm-memory = { version = "0.13", features = ["backend-mmap", "backend-atomic"] }
